[zookeeper]
hosts=zk:2281
tls_cert=/var/certs/certs/client.pem
tls_key=/var/certs/keys/clientkey.pem
tls_ca=/var/certs/certs/cacert.pem

[keystore]
password=secret

[scheduler]
tenant_config=/etc/zuul/main.yaml

[connection agent-git]
driver=git
baseurl=git://gitserver/
poll_delay=60

[database]
# Password supplied via variable interpolation from the compose environment.
dburi=mariadb+pymysql://zuul:%(ZUUL_MYSQL_PASSWORD)s@mysql/zuul

[web]
listen_address=0.0.0.0
port=9000
root=http://localhost:9000

[executor]
private_key_file=/var/certs/executor_id_rsa
trusted_rw_paths=/srv/static/logs

[auth zuul_operator]
driver=HS256
allow_authz_override=true
realm=zuul.local
client_id=zuul.local
issuer_id=zuul_operator
secret=exampleSecretPhase0

[webclient]
url=http://localhost:9000
verify_ssl=false
